### ISSUE TITLE
Header ma obrovsky space pokial logo ma iny pomer stran ako defaultne logo

### ISSUE THREAD

**Issue by ondond** [id-sk/id-sk-frontend#165]
Ked pomer stran loga je iny ako defaultne pouzite logo "slovensko.sk", tak ostava obrovsky cierny space.

Tieto riadky
https://github.com/id-sk/id-sk-frontend/blob/52e3fc1a603f079993dd036ad69818c9c34f76ef/src/idsk/components/header/_header.scss#L59

som overrideol nasledovne:
```css
.idsk-header__logotype>* {
  width: auto;
  height: auto;
  max-height: 30px;
}
```

Navyse je potrebne zmazat tento riadok https://github.com/id-sk/id-sk-frontend/blob/52e3fc1a603f079993dd036ad69818c9c34f76ef/src/idsk/components/header/_header.scss#L143

Resp. jeho override vyzera nasledovne
```css
.idsk-header__logo {
  width: auto;
}
```
