### ISSUE TITLE
Tlacidlo pre navrat na zaciatok stranky v rozsirenej paticke

### ISSUE THREAD

**Issue by oliverfindl** [id-sk/id-sk-frontend#299]
Velkost tlacidla pre navrat na zaciatok stranky v rozsirenej paticke neberie do uvahy zmenu velkosti fontu medzi tabletom a desktopom co ma za nasledok, ze pri tablete a mobile je toto tlacidlo 5px nad patickou.

https://github.com/id-sk/id-sk-frontend/blob/dd3cbec368f5dd487399566410d2a7254f2bb429/src/idsk/components/footer-extended/footer-extended.scss#L528-L532

Ukazka:

![Screenshot from 2021-10-02 17-10-52](https://user-images.githubusercontent.com/33978096/135722717-1767822d-8172-4f11-a432-e18cde6596ac.png)

Oprava:

```scss
@include govuk-media-query($until: tablet) {
	.idsk-footer-extended-up-button-div {
		height: 40px;
	}
}
```
